apiVersion: v1
kind: Service
metadata:
  labels:
    app: synthea-highmed
    argocd.argoproj.io/instance: synthea-highmed
  name: synthea-highmed
  namespace: synthea-highmed
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: synthea-highmed
