# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: {{.Values.global.argoNamespace}}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{.Values.projects.airflow.name}}
  source:
    repoURL: {{.Values.projects.airflow.repoURL}}
    path: charts/airflow
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
