apiVersion: v1
kind: Service
metadata:
  name: gpas
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ .port }}
    name: {{ .name }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}

