homepage:
  image:
    repository: ghcr.io/gethomepage/homepage
    tag: v0.9.2

  # Enable RBAC. RBAC is necessary to use Kubernetes integration
  enableRbac: true

  serviceAccount:
    # Specify a different service account name
    name: homepage
    # Create service account. Needed when RBAC is enabled.
    create: true

  service:
    main:
      ports:
        http:
          port: 3000

  controller:
    strategy: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  # Enable the ingress to expose Homepage to the network.
  ingress:
    main:
      enabled: true
      labels:
        # This label will enable discover of this deployment in Homepage
        gethomepage.dev/enabled: "true"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        # These annotations will configure how this deployment is shown in Homepage
        gethomepage.dev/name: "Homepage"
        gethomepage.dev/description: "A modern, secure, highly customizable application dashboard."
        gethomepage.dev/group: "A New Group"
        gethomepage.dev/icon: "homepage.png"
      ingressClassName: "nginx"
      hosts:
        - host: &host "homepage.dev.num-rdp.de"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: homepage-tls

  # All the config files for Homepage can be specified under their relevant config block.
  config:
    # To use an existing ConfigMap uncomment this line and specify the name
    # useExistingConfigMap: existing-homepage-configmap
    bookmarks:
      - Environments:
          - NUM Codex Production:
              - href: https://num-codex.de
                abbr: VG
          - NUM Codex Pre Prod:
              - href: https://num-codex.de
                abbr: VG
          - NUM Codex Staging:
              - href: https://staging.num-codex.de
                abbr: VG
          - NUM Codex Dev:
              - href: https://dev.num-codex.de
                abbr: VG
          - NUM RDP Develop:
              - href: https://develop.dev.num-rdp.de
                icon: https://upload.wikimedia.org/wikipedia/commons/3/36/SVA-Logo.png
                abbr: D
          - NUM RDP Test:
              - href: https://test.dev.num-rdp.de
                icon: https://upload.wikimedia.org/wikipedia/commons/3/36/SVA-Logo.png
                abbr: T
      - Mgmt:
          - Jira Backlog:
              - href: https://highmed-ev.atlassian.net/jira/software/projects/NUM/boards/1/backlog?epics=visible
                abbr: JB
                icon: atlassian-jira.svg
          - GWDG Rancher:
              - href: https://prod.rancher.gwdg.de
                abbr: R
                icon: rancher.svg
          - Swagger Develop:
              - href: https://num-portal.develop.dev.num-rdp.de/swagger-ui/index.html
                icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
                abbr: Dev
          - Swagger Test:
              - href: https://num-portal.test.dev.num-rdp.de/swagger-ui/index.html
                icon: https://upload.wikimedia.org/wikipedia/commons/a/ab/Swagger-logo.png
                abbr: Tst
          - RDP DEV Grafana:
              - href: https://prod.rancher.gwdg.de/k8s/clusters/c-m-c2mr5hcb/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/?orgId=1
                abbr: G
                icon: grafana.svg
          - RDP DEV ArgoCD:
              - href: https://argocd.dev.num-rdp.de/applications
                abbr: ARGO
                icon: argocd.svg
          - NUM-RDP Keycloak Develop:
              - href: https://keycloak.develop.dev.num-rdp.de/auth
                abbr: Dev
                icon: keycloak.svg
          - NUM-RDP Keycloak Test:
              - href: https://keycloak.test.dev.num-rdp.de/auth
                icon: keycloak.svg
                abbr: Tst
      - Docs:
          - NUM CRR Documentation:
              - abbr: CRR
                href: https://github.com/NUM-Forschungsdatenplattform/num-crr-documentation
                icon: github.svg
          - NUM Portal:
              - abbr: P
                href: https://github.com/NUM-Forschungsdatenplattform/num-portal
                icon: github.svg
          - NUM Portal Webapp:
              - abbr: Web
                href: https://github.com/NUM-Forschungsdatenplattform/num-portal-webapp
                icon: github.svg
          - NUM Fhir Bridge:
              - abbr: FB
                href: https://github.com/NUM-Forschungsdatenplattform/num-fhir-bridge
                icon: github.svg
          - NUM AQL Editor:
              - abbr: AQL
                href: https://github.com/NUM-Forschungsdatenplattform/num-fhir-bridge
                icon: github.svg
          - Ehrbase:
              - abbr: EB
                href: https://github.com/ehrbase/ehrbase
          - Ehrbase SDK:
              - abbr: SDK
                href: https://github.com/ehrbase/openEHR_SDK
          - NUM Ops Guide:
              - abbr: NOG
                href: https://github.com/NUM-Forschungsdatenplattform/num-ops-guide
                icon: github.svg
          - NUM Helm Charts:
              - abbr: NHC
                href: https://github.com/NUM-Forschungsdatenplattform/num-helm-charts
                icon: github.svg
          - Keycloak Configurations:
              - abbr: KC
                href: https://github.com/NUM-Forschungsdatenplattform/keycloak-configurations
                icon: github.svg

    services:
    widgets:
      - resources:
          # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
          backend: resources
          expanded: false
          cpu: false
          memory:
            false
            #    - search:
            #        provider: duckduckgo
            #        target: _blank
      ## Uncomment to enable Kubernetes integration
    #   - kubernetes:
    #       cluster:
    #         show: false
    #         cpu: true
    #         memory: true
    #         showLabel: true
    #         label: "cluster"
    #       nodes:
    #         show: true
    #         cpu: true
    #         memory: true
    #         showLabel: true
    # kubernetes:
    #   # change mode to 'cluster' to use RBAC service account
    #   mode: cluster
    docker:
    settings:
      theme: light
  persistence:
    logs:
      enabled: true
      type: emptyDir
      mountPath: /app/config/logs
  resources:
    requests:
      memory: 10Mi
      cpu: 10m
    limits:
      memory: 200Mi
      cpu: 500m
