apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.appConfig.postgresqlDatabase }}-postgres
spec:
  instances: 1
  bootstrap:
    initdb:
      database: {{ .Values.appConfig.postgresqlDatabase }}
      postInitApplicationSQL:
      - "ALTER USER {{ .Values.appConfig.postgresqlDatabase }} CREATEROLE;"
  monitoring:
    enablePodMonitor: true
  storage:
    size: 1Gi
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      destinationPath: s3://codex-postgres-backup/cloudnative-pg/{{ .Release.Namespace }}/{{ .Values.appConfig.postgresqlDatabase }}
      endpointURL: https://s3.fs.gwdg.de
      s3Credentials:
        accessKeyId:
          name: s3-credentials
          key: accessKeyId
        secretAccessKey:
          name: s3-credentials
          key: secretAccessKey
