apiVersion: v1
kind: Service
metadata:
  labels:
    app: openfhir
    argocd.argoproj.io/instance: open-fhir
  name: openfhir
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8090
  selector:
    app: openfhir
