victoria-logs-single:
  fluent-bit:
    enabled: true
    daemonSetVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
    daemonSetVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
  server:
    extraArgs:
      envflag.enable: "true"
      loggerFormat: json
    #
    # disable http-auth
    #
    #   httpAuth.username: "%{HTTP_AUTH_USERNAME}"
    #   httpAuth.password: "%{HTTP_AUTH_PASSWORD}"
    # env:
    #   - name: HTTP_AUTH_USERNAME
    #     valueFrom:
    #       secretKeyRef:
    #         key:  username
    #         name: http-auth-scecret
    #   - name: HTTP_AUTH_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         key:  password
    #         name: http-auth-scecret
    persistentVolume:
      enabled: true
      storageClass: ssd
      size: 50Gi
      accessModes:
        - ReadWriteOnce
      mountPath: /storage
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
