victoria-logs-single:
  fluent-bit:
    enabled: true
    daemonSetVolumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
    daemonSetVolumeMounts:
      - name: varlog
        mountPath: /var/log
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
  server:
    enabled: true
    extraArgs:
      envflag.enable: "true"
      loggerFormat: json
    persistentVolume:
      enabled: true
      storageClass: ssd
      size: 50Gi
      accessModes:
        - ReadWriteOnce
      mountPath: /storage
    resources:
      limits:
        cpu: 1
        memory: 512Mi
      requests:
        cpu: 500m
        memory: 512Mi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-staging"
      pathType: Prefix
      hosts:
        - name: logs.rdp-dev.ingress.k8s.highmed.org
          path: /
          port: http

      tls:
        - secretName: victoria-logs-letsencrypt-staging-tls
          hosts:
          - logs.rdp-dev.ingress.k8s.highmed.org
