apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fhirbridge
  name: fhirbridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhirbridge
  template:
    metadata:
      labels:
        app: fhirbridge
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - image: ghcr.io/num-forschungsdatenplattform/fhirbridge:latest
          name: fhirbridge
          ports:
            - containerPort: 8090
          env:
            - name: DB_TYPE
              value: postgres
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  key: jdbc-uri
                  name: {{ .Values.appConfig.postgresqlDatabaseSecretName }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ .Values.appConfig.postgresqlDatabaseSecretName }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ .Values.appConfig.postgresqlDatabaseSecretName }}
