apiVersion: v1
kind: Service
metadata:
  labels:
    app: fhirbridge
    argocd.argoproj.io/instance: fhir-bridge
  name: fhirbridge
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8888
  selector:
    app: fhirbridge
