global:
  argoNamespace: argo
  repoURL: https://github.com/NUM-Forschungsdatenplattform/num-ops-guide.git
  numHelmChartsRepoURL: git@github.com:NUM-Forschungsdatenplattform/num-helm-charts.git
  numHelmChartsBranch: rdp-dev

  sertigo:
    enabled: true

projects:
  devCluster:
    description: NUM RDP Dev Cluster
    name: cluster
  devEnv:
    description: NUM RDP Dev Environments
    name: environments
  RDPdevelop:
    description: NUM RDP Develop Environment
    name: rdp-develop

applications:
  developEnv:
    enabled: true
    namespace: develop
    helmValueFile: deployment-values/central-research-repository/develop-values.yaml
  devEnv:
    enabled: false
    namespace: dev
    helmValueFile: deployment-values/central-research-repository/development-values.yaml
  opsEnv:
    enabled: false
    namespace: ops
    helmValueFile: deployment-values/central-research-repository/ops-values.yaml
  uweEnv:
    enabled: false
    namespace: uwe
    helmValueFile: deployment-values/central-research-repository/uwe-values.yaml
  testEnv:
    enabled: true
    namespace: test
    helmValueFile: deployment-values/central-research-repository/test-values.yaml
