global:
  argoNamespace: argo
  repoURL: https://github.com/NUM-Forschungsdatenplattform/num-ops-guide.git
  numHelmChartsRepoURL: git@github.com:NUM-Forschungsdatenplattform/num-helm-charts.git
  numHelmChartsBranch: rdp-dev

projects:
  devCluster:
    description: NUM RDP Dev Cluster
    name: dev-cluster
  devEnv:
    description: NUM RDP Dev Environments
    name: dev-envs

applications:
  # devEnv:
  #   name: dev-env
  #   namespace: dev
  #   helmValueFile: deployment-values/central-research-repository/development-values.yaml
  opsEnv:
    name: ops-env
    namespace: ops
    helmValueFile: deployment-values/central-research-repository/ops-values.yaml
  # uweEnv:
  #   name: uwe
  #   namespace: uwe
  #   helmValueFile: deployment-values/central-research-repository/uwe-values.yaml
  testEnv:
    name: test-env
    namespace: test
    helmValueFile: deployment-values/central-research-repository/test-values.yaml
