---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.rdp-dev }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.global.namespaces.rdp-dev }}
  namespace: {{ .Values.global.namespaces.argocd }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: {{ .Values.global.namespaces.rdp-dev }} Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: {{ .Values.global.namespaces.rdp-dev }}
    server: https://kubernetes.default.svc
---  
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: num-rdp
  namespace: {{ .Values.global.namespaces.argocd }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.namespaces.rdp-dev }}
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/num-rdp
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespaces.argocd }}
  syncPolicy:
    automated:
      selfHeal: true
