---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespaces.argocd }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.global.namespaces.argocd }}-project
  namespace: {{ .Values.global.namespaces.argocd }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: ArgoCD Project
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
---  
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: {{ .Values.global.namespaces.argocd }}

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.global.namespaces.argocd }}-project
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespaces.argocd }}
  syncPolicy:
    automated:
      selfHeal: true
