apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: {{ .Values.global.namespaces.argocd }}

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/root-app/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.global.namespaces.argocd }}
  syncPolicy:
    automated:
      selfHeal: true
