---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: rdp-dev-ehrstore
spec:
  encryptedData:
    accessKeyId: AgB9LYdmYM2Iqu5anCZ69V7bEUBjCMSMcsLT/wXuiFruLPmyrQwlsgPvCCPBPa2sWb8XKBiuUmRu0+OB4K+dl1/lKwkJBYggBq4E+dydT8BrzxmF9DEkpPbr3g/YAWbXqKWRVbr9QdKjTKUsliG74v8z273MU+1LLSRZYuiADzpCsUIs/CQNeKcRpQcMJH8xcxcNW2ShOEQrKFdOwZnG2qeM5AOHbyAu4zl4zndjGh7JUjhHxDRnyZhA2SGJrImQmrQyrvy0JxgPxvPAxvi63dnpddr/iVsSoT+lqff1k7pEwyBlXx2hD4Z2yIC+kFwPNY48vzfN/s03QkldJqmABZe63XdptYRq1wjrWvm8XbI1QXpV9rlHwicvHNjYE0ZHvZbqcsUkSD6YuXuHWjJlHTQjfP/3ukUmmlOeTN3g6VBqIxZH5zg6Dq1vOZARxcgFPvFrnmFpsNsjJzvvnqUEM5SJrCTA72DxAIRWDac0Iwgl9QOqQ/h2tKNqkg5lykbjI11TM3h52FjqvolTyVmvd1VxDAbFRitNdZWBYcwInUAQZZz1f3vvshZ0tiSZdxj6tgS5zJI4lEDBI1UzSTqyQpvD+eRHR9vm4v5Qo/HyWqyHG1AAed7LNBAFG7VR1pq+SkBGO2M07Yok65wzO5N+IxwwqOWldGCozFiSkOhgDosYSQwforVSN6Q9IN+7m+wN2stUTJOS4twjxXBSun6d4caDGIKRAQ==
    secretAccessKey: AgBDlJQwAghUpSR6y1Kz5Pj5mQxNrutRs8DbcI/0WnVZ17DWOBzNj8SoRc+R1a294GvEMUtwqYXnmyF/dTEb1PXiw7kgKQmihHADB35rJBnRhcP1/xHg6iv2bOt82nheuq0omDPdCf0OYXHZaDKDOsyPaWUj3xgAoiH4I5Wg7E772FL2RX/HQte9kWwgNSiTfmOsMGDx74N9nRqzi2b7n7i1sTlDpwtSoEOswvL0j98Nx1mXgqt4lETiOymv45QGlpvxJYyFkuovbrncS12hlMZiEweBgyowOrW+Wq34MLxK4jrrJ4Wvp6G96tFdfWlR0zD1tBgbIEvSH9tFtx2mcRX8pJGUpEieoLSttUXt3lag9O5a3lPMjjFzcl0ca7fWK73n/OZ658TU8aB1AOBo5vyqn7x3zSGQnzXoHv8flPzWncx1G7g9ySy7V32e5XUFkI7l/5P9pIargW7WekwTQekVnRq7m6IfB6yiS6vEE1lOlWvff4944yv/OxuYeUY4rchuYuDuNr0+QvsiHMi4fXWEqGVMQj+gZNtcnPTC6Y3VH/cSOVR9gXsh5kSksHDd4NcQiB11tol/paD311uQwHj0FQIjX7GE1NiKWgiflhnFPxiqDh+d9E1VkgjEIEYciWzt20RJqPGQ23Z15wcOmTwNxAVNBNvC5yT72arnmW/RNbR0jz8cpJXFqOYCyXOIwUOATIw9PMBXEwu1/vyQRvVILy/LjF1yRJ1/joYR7PVj2Z8tAo0FtLpN
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: rdp-dev-ehrstore
    type: Opaque
