apiVersion: v1
kind: Secret
metadata:
  name: num-ops-guide-repository
  namespace: ops-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:NUM-Forschungsdatenplattform/num-ops-guide.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----