apiVersion: v1
kind: Secret
metadata:
  name: num-helm-chart-repo-secret
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: num-helm-charts-repo
  type: git
  url: git@github.com:NUM-Forschungsdatenplattform/num-helm-chart.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    ...
    -----END OPENSSH PRIVATE KEY-----