global:
  env: develop 

replicaCount: 1

image:
  repository: mosaicgreifswald/gpas
  tag: 2024.3.0
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-login-secret

service:
  type: ClusterIP
  ports:
    - port: 8787
      name: debug
    - port: 8080
      name: webui
    - port: 9990
      name: healthcheck

env:
  WF_ADMIN_PASS: admin
  TTP_FHIR_GICS_TERMINOLOGY_FOLDER value: gics/terminology
  WF_HEALTHCHECK_URLS: http://localhost:8080/

resources: {}
