# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epix-wildfly
  namespace: {{ .Values.global.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.projects.greifwaldApps.name }}
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/greifswald-apps/epix-wildfly
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.projects.greifwaldApps.name }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
