# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epix-mysql
  namespace: {{ .Values.global.argoNamespace }}
spec:
  project: {{ .Values.projects.greifswaldApps.name }}
  source:
    chart: mysql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 11.1.20
    helm:
      values: |
        primary:
          startupProbe: 
            enabled: false
          readinessProbe: 
            enabled: false
          livenessProbe: 
            enabled: false
        initdbScriptsConfigMap: epix-init-db-config-map
        extraEnvVars:
          - name: MYSQL_ROOT_PASSWORD
            value: "root"
          - name: TZ
            value: "Europe/Berlin"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.projects.greifswaldApps.name }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
