# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpas-mysql
  namespace: {{ .Values.global.argoNamespace }}
spec:
  project: {{ .Values.projects.greifswaldApps.name }}
  source:
    chart: mysql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 11.1.20
    helm:
      values: |
        initdbScriptsConfigMap: gpas-init-db-config-map
        auth:
          rootPassword: "newRootPassword123"
        extraEnvVars:
          - name: MYSQL_ROOT_PASSWORD
            value: "newRootPassword123"
          - name: TZ
            value: "Europe/Berlin"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.projects.greifswaldApps.name }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
