apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-access-binding
subjects:
  - kind: ServiceAccount
    name: cloudnative-pg
    namespace: cloudnative-pg
roleRef:
  kind: ClusterRole
  name: crd-access # The ClusterRole you created
  apiGroup: rbac.authorization.k8s.io
