tenant:
  tenant:
    name: develop-minio-tenant
    pools:
      - servers: 2
        name: pool-0
        volumesPerServer: 2
        size: 1Gi
        storageClassName: ssd
    certificate:
      requestAutoCert: true
    buckets:
      - name: develop-ehrshow
