apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hapi-fhir
  name: hapi-fhir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapi-fhir
  template:
    metadata:
      labels:
        app: hapi-fhir
    spec:
      containers:
      - image: hapiproject/hapi:latest
        name: hapi-fhir
