apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hapifhir
  name: hapifhir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hapifhir
  template:
    metadata:
      labels:
        app: hapifhir
    spec:
      containers:
      - image: hapiproject/hapi:latest
        name: hapifhir
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              key: jdbc-uri
              name: {{ .Values.appConfig.postgresqlDatabaseSecretName }}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ .Values.appConfig.postgresqlDatabaseSecretName }}
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ .Values.appConfig.postgresqlDatabaseSecretName }}
        - name: SPRING_DATASOURCE_DRIVERCLASSNAME
          value: org.postgresql.Driver
        - name: spring.jpa.properties.hibernate.dialect
          value: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
        - name: HAPI_FHIR_USE_APACHE_ADDRESS_STRATEGY
          value: "true"
