argo-cd:
  global:
    domain: argocd.dev.num-rdp.de
    logging:
      format: json
      # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
      level: info

  configs:
    params:
      server.insecure: true
    secret:
      extra:
        oidc.keycloak.clientSecret: UgBj6E3ITFHomVAQUuimPy3URUorpNqu
    rbac:
      policy.csv: |
        g, ArgoCDAdmins, role:admin
        g, ArgoCDUser, role:readonly
    cm:
      url: https://argocd.dev.num-rdp.de
      oidc.config: |
        name: Keycloak
        issuer: https://keycloak.dev.num-rdp.de/auth/realms/master
        clientID: argocd
        clientSecret: $oidc.keycloak.clientSecret
        requestedScopes: ["openid", "profile", "email", "groups"]

  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false

  server:
    # SSL Termination at Ingress Controller
    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: argocd.dev.num-rdp.de
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      extraTls:
        - hosts:
          - argocd.dev.num-rdp.de
          secretName: argocd-letsencrypt-prod-tls
