argo-cd:
  global:
    domain: argocd.rdp-dev.ingress.k8s.highmed.org
    logging:
      format: json
      # -- Set the global logging level. One of: `debug`, `info`, `warn` or `error`
      level: info

  configs:
    params:
      server.insecure: true

  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
