apiVersion: v1
kind: Service
metadata:
  labels:
    app: ehrbase
    argocd.argoproj.io/instance: ehrbase
  name: ehrbase
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ehrbase
