apiVersion: v1
kind: ConfigMap
metadata:
  name: ehrstore-cloud-db-setup
data:
  ehrstore-cloud-db-setup.sql: |
    -- This script needs to be run as database superuser in order to create the database
    -- These operations can not be run by Flyway as they require super user privileged
    -- and/or can not be installed inside a transaction.
    --
    -- Extentions are installed in a separate schema called 'ext'
    --
    -- For production servers these operations should be performed by a configuration
    -- management system.
    --
    -- If the username, password or database is changed, they also need to be changed
    -- in the root pom.xml file.
    --
    -- On *NIX run this using:
    --
    --   sudo -u postgres psql < createdb.sql
    --
    -- You only have to run this script once.
    --
    -- THIS WILL NOT CREATE THE ENTIRE DATABASE!
    -- It only contains those operations which require superuser privileges.
    -- The actual database schema is managed by flyway.
    --

    CREATE ROLE ehrstore WITH LOGIN PASSWORD 'ehrstore';
    CREATE ROLE ehrstore_restricted WITH LOGIN PASSWORD 'ehrstore_restricted';
    CREATE DATABASE ehrstore ENCODING 'UTF-8' LOCALE 'C' TEMPLATE template0;
    GRANT ALL PRIVILEGES ON DATABASE ehrstore TO ehrstore;
    GRANT ALL PRIVILEGES ON DATABASE ehrstore TO ehrstore_restricted;


    \c ehrstore
    REVOKE CREATE ON SCHEMA public from PUBLIC;
    CREATE SCHEMA IF NOT EXISTS ehr AUTHORIZATION ehrstore;
    GRANT USAGE ON SCHEMA ehr to ehrstore_restricted;
    ALTER DEFAULT PRIVILEGES FOR USER ehrstore IN SCHEMA ehr GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ehrstore_restricted;
    ALTER DEFAULT PRIVILEGES FOR USER ehrstore IN SCHEMA ehr GRANT SELECT ON SEQUENCES TO ehrstore_restricted;

    CREATE SCHEMA IF NOT EXISTS ext AUTHORIZATION ehrstore;
    GRANT USAGE ON SCHEMA ext to ehrstore_restricted;

    CREATE EXTENSION IF NOT EXISTS "uuid-ossp" SCHEMA ext;

    -- setup the search_patch so the extensions can be found
    ALTER DATABASE ehrstore SET search_path TO ext;
    -- ensure INTERVAL is ISO8601 encoded
    ALTER DATABASE ehrstore SET intervalstyle = 'iso_8601';

    ALTER FUNCTION jsonb_path_query(jsonb,jsonpath,jsonb,boolean) ROWS 1
