{{- if .Values.global.sertigo.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: sertigo
  namespace: cert-manager
spec:
  acme:
    email: kubernetes-admins@gwdg.de
    preferredChain: ""
    privateKeySecretRef:
      name: sertigo-cluster-issuer-key
    server: https://acme.sectigo.com/v2/OV
    solvers:
    - http01:
        ingress:
          class: nginx
          serviceType: ClusterIP
    disableAccountKeyGeneration: true
{{- end }}
