# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epix-mysql
  namespace: {{ .Values.global.argoNamespace }}
spec:
  project: {{ .Values.projects.ePIX.name }}
  source:
    chart: mysql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 11.1.20
    helm:
      values: |
        initdbScriptsConfigMap: "epix-init-db-config-map"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: {{ .Values.projects.ePIX.name }}
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
