apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: {{ .Values.global.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.projects.devCluster.name }}
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/homepage
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
