apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-logs
  namespace: {{ .Values.global.argoNamespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.projects.devCluster.name }}
  source:
    repoURL: {{ .Values.global.repoURL }}
    path: charts/victoria-logs
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: victoria-logs
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: core
      kind: Secret
      name: basic-auth-generated-secret
      namespace: victoria-logs
      jsonPointers:
        - /data
        - /metadata
