# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/argoproj.io/application_v1alpha1.json
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: {{ .Values.global.argoNamespace }}
spec:
  project: {{ .Values.projects.devCluster.name }}
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.15.0
    helm:
      releaseName: sealed-secrets
      parameters:
        - name: 'fullnameOverride'
          value: 'sealed-secrets-controller'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
