apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: epix-mysql
  namespace: {{ .Values.global.argoNamespace }}
spec:
  project: {{ .Values.projects.RDPdevelop.name }}
  source:
    chart: mysql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 11.1.20
    helm:
  #    valuesObject:
  #      initdbScriptsConfigMap: epix-init-db-config-map
  #       primary:
  #         livenessProbe:
  #           enabled: false
  #         readinessProbe:
  #           enabled: false
  #         startupProbe:
  #           enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: epix
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
