---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: airflow-admin-user
  namespace: airflow
spec:
  encryptedData:
    password: AgAvui5JTM6QBYAsfXUdTNDefKnKsUI2z79bSUxDjwpCr2iGifjo/cjwG6nr4WFtGRdndj3ZyXHnR/5jgSDTNl1S/tN43kPGl2dggEtSmAeqFU451+l0c95FMXfcS+h9NJi00Ltd1jTBGTWzQIJKv1Df8G9CKg5lELUiWlqP8y5NdVFkX1p/ow5SviEKU38UjOPyi0hyKtba1Q0EG5a0zY0/6RIymfkaR8oai72QsZ8xsziXBidDJ/CuUuhgoxPLD6bgU16/1dw4doAR+bNMOYHtDKEtaOlgx9fo/+gfpPwTznKPM9bwgYe3QLgnvUYmBoJE7AgzhsnVc5ZnBZK+mzLaiu76bVR1563T1goeVqrQKXlEuBOkcT+Ma2Sz1TtA2xmGL0ergxbgwmPjFmGZRbngFJRD1+EcyMe5TKmeai5CKJgNkSL9BflxKUhlWBPmQk9EbmVOVsTSXS5qJlxl9Oa/dt1Ou0b+/tqzxDbCeBTCKypDTDzZ6NEAIbNnVRjgHyMjG/txSbr5QquMW9djPagGOtYoePoSqvOWDhHBFg8s/aTc8+n+62hlp0l5PyAoYs8e2ZgpqglUWIJZUjc23YZKUMre0gH0n7ZL4VUT3yTtofFEt/wikqVc6Q5llmHmpulMDDxXEiUxQRPHIwUJU+e01A8/NsVKETZICTjEz2B74Gz3MwqvlSlUWZv9ARt33F/JDq9ui1DMRfiG+o4wQxlW0TYyd79WY2k=
    username: AgAVZYzgjPygWnAagiWLUwlE20Au8mC73Xc3MSh51mh4qduYw50SIkz7Gp189BHcHhOs/KFYyxOEZxOFVpTpG1ieTt3OGF4njtGt2TBJj1B9rnxs7NhhtaLXB5lrKS7bqWBvXlZiO/IkFwJCJjVJT2/k3QbnG6StuY1NGqU88C301C15eVDqhZeqOM+Vj0a9PTE5+cbtFCpBWQiupyklKlljXus415+yilwM8VCuQObyF6taYvXPTofVOHu2wkxYx3TBljDqVvLFWUF1AQzlJE0MdjJfEGguqwUek9QyaBNcCkcqG+ISM1oy6lKHLdr2iEC7CaNbdYhx4C7Q4UrI25zdpWz+PVwJfTYzFtTROkSeCIYRqtjTeSomFqqPWgE3D1XfEDLlSSqiCkTrnKOBKx9SekHVsosTr6QNAlb7KlrNlXWtm8/13nbgUONq7fC2+TSUQgpAGhQ2sfHmsfP/1zKmuRoiJZlu4vxMhfFQzlPwuZqcxoufXsywTFv4bNjxcNTfVUZ9pSql09UuUlKv8S5HxX/eawdZuaeZvLMOX0VJbYeJymo2B/9MQ4xy9rgZdhPjFxxOjIr+aSLVOKQsejS/D+BPgILvzK13ma12ZmFAKgAdIQ5TjIyaSuf87j8C95solFZqt3Azyg7itA/6U3bjKBxknGsYB0YS6mkDkyGq9L0WYK9d54NalVPwzwoolu8PXAHVhA==
  template:
    metadata:
      creationTimestamp: null
      name: airflow-admin-user
      namespace: airflow
    type: Opaque
