---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: imagepullsecret-github-packages
  namespace: develop-ehrshow
spec:
  encryptedData:
    .dockerconfigjson: AgBdonKuWS8YJQvP9pursftQB9D0RywBga1cYo/g9k2nvFlDxgBkUuvgv2j6QgktlgYRLYwrJGvhxdJYKik6imj4SKL/+/Hp7a7tN1d3m4w0slxMUCwUi91o+Dg6P3k3cnQE7EUqIDEX+lMaXEXmcctm+HWWvs6Q+F6+dph5CqB6HBgM7XKFOorDg9uc/JRo2EPdMnpqyz+5/lZONgnDaeW+zDxqgYZ/E52kT4/9CFtnnkHKBUcxDUtLIkYYuiPGqlhZ06Vq2Z9m7GRrmULzAnM6ibtEzYdk4Ia84Y09IJSZAWkcD+Xl/mi0QO/mWsI9gYzuFP3+Tu6BwRlZtct+w9DHOJGEqQgVzKOuYrDj4md6NqexoZF3CydEdeZ9XoQWs1BH7jhgVOI9UklEj2F/3VdFkgAHMp+iv0pVrxoeQFhoOU5NCTSw2AhHTHSs/N5h+yK9RMbpr1JY3JYB2hPK2kHNEbjHuYWSjp4dDcgvZJeEKvqJhx/lXq6ZnLR1cxwki9iRotKx75XU/4v6S0rGQLwnboimqZoVRa4hgOu6JqMSwVGwvqHE1pDPKCbapOdgoXszxJbtEzUPyfT7z3nWws+oOEWGJZaZ6qOcKV0eD5uskzaShsh9/78zE6xB6JspuxlZ89u/3ZmYx/eGO+14LCIehl8YyKejFybPg4EodKQZEExUsOAmLB/sGHico8eFNyVHk/vux4xa/Jx5VWcZItUciKd7D15GnE2Ron2mjEdpYDcaKAt/k/7cb3xSgpt+Md+JK8jHUl4YxtmteNK5PQXV2flxs/5xsH4MUw1dAeZhTNtAow8O4Djlyjrl0E/8b8TpQlgPXA0a/BPGzaBbJCyJCmBmlqSMe67A37tyjFyOxA0kHSA=
  template:
    metadata:
      creationTimestamp: null
      name: imagepullsecret-github-packages
      namespace: develop-ehrshow
    type: kubernetes.io/dockerconfigjson
