---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-keycloak-admin
  namespace: test
spec:
  encryptedData:
    password: AgCMDux9B2txZxIbQdB9o2tZia3XcoInJmhxj2HCogDOFnREv2O/5illDHCv1lK9MRb/1MZCyOmfOls508m7CyIR9gvJUIrekqczZ0nMeAYw8mKlsedefIFlWabnMRD8Txgw94H4LejCCCqwsGWmXtQ03KXOHLwKWNyCRs1O56IYwcyAirjkL8eK3FF30Db1mmWRsEiJvsucyfYweqskii80ZZjHfD7IqlwG/A++u7rUaLZ0eqx2gFkNpTltQfK8af1frOhuRMKEem/tlLvJp80VR2cUUQv/VHKtKwNQZMRCo8JQwDz52YrUHVMU93ZRlfhHSEyLBQ6nTXijMjEIyyg1xoSYYt5Ntp7gbl8LdWSPSaMdDsypYsYZxmkfjouDnflD8c3/YrORCxXF43iNCIubywf8x1+bh2ClALwZDp59CWYVhLIN7LflQML1TSZe8amnb4PU8HlVJbknBfS8U/hM3sYDhciqwvEvf1mWgDYJV2mVWDLyyLkx/tuX+jH0ktqYPRQrmDrBLN5RNFgMnLWHn3MG6+stf5kA6pzSLMlRtNoKoL98xzBBJO3XFxKD8KH6VuJncaBoOL+Np2xu5D/n6hU36+RSBtkACzOIi6fkfViXNZPiLZU+R5JHTLHpddPT+7n2Yfe+2zzBwuyZ/YpDomCevIiHWmkt3M9wydr0LZJMMFtg2lqqB6AxHBK/Pn2mT5CX6ddDvobIQ+EwQloc
    user: AgC4Svlq2OoVvnUkh7iJqSsKasXfoeOVEzJprcEtGbag2mo5VGDEQoQ0TDEMVmJqpSEKRx3CBDrEvwwrPdM3INcOx8PcfGJ/fU1ZV6k2fJyp7mcenI0EzRprK6WPzEWscMDSh57ZD9FsPk3don2FnljHz2L1ng/xxmp+cqiFxu6RHpsiw2ySZJpVo0WAfdvZ+GWCOTLOt3MDGrHFF87jE30lp7tVnTM8ndgtIDIPktK9rrrGuqIoC6GXYoVlVVNpifkDPU5lix69/pIbWr6NNsiEfLXROTJChJH8ug9ZeXfsKme/0H4OoMl6F6MRyJsjyT6CdWQXNYFHk/TDE3Sb/uL/uIKCyyD/cYvbGJLYCMUUkvWUONwCEl92DsN5riogcdZqcm/E8nDci9FDc30L3RL9ZW7MxJNcedAtOIMCG83ftng9v6QiLlmZ7dKIeN82sMgm5vTBPNMBWyLR68jmmy7tgdCAH7X/1i2okQbye7vjBMLLwc2VC/ESrzFSzvoxtcEdDuAI7jtT+Drbto9VyH03hVbkfS77wIFaFzrAp1VNP4HKlUerPo3ynq0MPL4Tzw4nTbp83BDI+uj22MwDYp4ltt4DsTFPDmUYaIFOYkZMmk2ZjE72UY1nTtW/fiIifYFFOdqyUqu/3rorYZxVvazkKszj7a5u5vItySlNwN5QhIIQHGSe4ek18vfODUSqfh+8nc7oZw==
  template:
    metadata:
      creationTimestamp: null
      name: test-keycloak-admin
      namespace: test
    type: Opaque
