---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: s3-credentials
  namespace: ehrshow
spec:
  encryptedData:
    accessKeyId: AgCrQqxYD6E4n/ZEP4OEmiwmRFFaHyzLB5hCUtOkgb4zf3vMd7XmqdK0EnOkovuR6Fq2uYgLuxivBBtc+28O8vf0sqrI85XOjSh3ABya3EaqIvzvMZ1j3GyOFJTTVEIveyNs0tOS/2fhzMYHB7BWxHsLHkFXzVYjTz1ROL2f7sH9qMN8ScGkXqfE7o3zoLH8wNeiLJjShs0HZfrdKA/CgqI6Nu3LUe0aNaqLKfJDi6pjcPtV6afWDez948I6fhKr26cAdPqVUqpDbHikyzqRQVku5VWypTlivb+vSFDX1VJYQfwWoBhUexGJMIqvU3eQ443vQ4sJmH+PNt7RIuP15hH9fNMBRpoy1w0/5s8hG3dYCqKD2YqXpYgrf+8QYz8Dj29YEAK8ZlVhBHjPjG9jHpQNtX6nMDx1+8krGEOi2fSdCD1M6/cDkcntWnt2NZqUhMmHS9/pBfM85y3GNrM/fC7HuLLHvRL/n4NKkEnxFmcIUoAxN0k4LoeBhF5kzzNNbRdMWI0/C/oO6Ev7ye3KYyWIvD+sbG52GweH9X7dAnJfHc9dUh2w26V/i/1o4/o99ew13ZutPnG76hnYd8mHyL1BC/8558tRuKGorgMGbhaDwaMR/OEgarnrON6CYk3WgZqYzx5nhk1ZVtzlJowPRqt0f4qAxPyre2mLVwxvLuc0xU4zEX/WhqI/2bDUDKctfoJSulx30p0M6wJ86LQWjSxBXRgoEg==
    secretAccessKey: AgAvJPAK016OcznZlb1OohTzyHxLWfDrhbfAgEEZtFb/bgdpXcK+LgVWuP+vfyTnvidmvb33XC3n8dbuMMnaOLP6LQFhrQPM1SycxLIcftVdgy5/1duuVu4pRotPVSdHcda4uNoEplYWsAnlx75cy4BurmpJjokVWPNZ3eVEnM7E3akNEE0oNOxNPPWixWLTcqT62AFyY5D+8LBApUCduynPNS6sF2lFWe+2b0xGElX81djU0+hf77PJ0E1OAWb/HSpM/dEGuYRUBFiosuR/NPU1NCXbd23hzX+4oHoFsJ6qL2RUx8EJ+jIFm5B7x5G7pcReEGpuWXD8mdDCC3wlVzOHR+c6xQNogy+AE0jN3k+AG0otEfpoxmiLVMEQRWZpsMqEATtNjiSNI53hZYWypQ7O7O9o1D/WXeWHJwBSsHT3Egxd+RbVI+X17MlZfK0PHtpGUgK/5F2buoifeAYg+ALHQX21zGCPvYNVl16C8z0upsbr7QEhB/qfP+y0/1L7TVayrwQ35uizUWYqjFFU2d26fpukoXgKb11wACLJBQvTw60VTfQqFHE9jo35GuH68YwjJSiHawa5MzQIDXJc42uMeTu4MDgQChq1xWmRuaXScpLZN4OQf8w45p0v7kwirUOCFN+H8DxrEBEomRmNNSqQXp5jdBHlnJlWbSCeKSxH9bjDzxMgDsuI0NBINZxYbbNPA+EGdSm+Qf9FRtmqyzxUux22bM3S4nh08zR+wAGWLlCALB1CUbD3
  template:
    metadata:
      creationTimestamp: null
      name: s3-credentials
      namespace: ehrshow
    type: Opaque
