{{- $username := printf "%s-%s" "u" (randAlphaNum 16) | b64enc | quote }}
{{- $password := printf "%s-%s" "p" (randAlphaNum 32) | b64enc | quote }}
{{- $lookup := "secret not found" }}

{{- $existingSecret := (lookup "v1" "Secret" "victoria-logs" "basic-auth-generated-secret") }}
{{- if $existingSecret }}
{{- $username = index $existingSecret.data "username" }}
{{- $password = index $existingSecret.data "password" }}
{{- $lookup = "secret found" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-generated-secret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ $username }}
  password: {{ $password }}
  lookup: {{ $lookup }}
