apiVersion: v1
kind: Secret
metadata:
  name: http-auth-scecret
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  username: {{ printf "%s-%s" "u" (randAlphaNum 16) | b64enc | quote }}
  password: {{ printf "%s-%s" "p" (randAlphaNum 32) | b64enc | quote }}