---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-login-secret
  namespace: epix-test
spec:
  encryptedData:
    .dockerconfigjson: AgBmQKvvNVewsKCSe1ideZWAbj1rPe1ifrIjAFuH66J5ugcLUP6/JufNVSYPfg0/+W2IGfl0qVTcZmUa/Uk8sGojfensti5NaFmf1Ms/oTevesOMCrdjDkQg7FggXRapsosR/h42ZFoZ8uXjtxcJzov6uN5n5c3TYHcSK4Yup937ZQ9R3wSL6G3Dm8O5AigVF64bZbVphyzivCmMRgdb+COzgTsKQ+IUrnua1dhGefKl10KfZHeDHSoWLvR0ZqntE9oqXzL2tDO0MVtxNCws3KjYdMgTpf808euc/kMXaK4RNkgdKDpZKWWdnXMu0s4e7bcIOXfksVQQ7Iw3pLJa+PQN3MK4nM+dDcD//L+NaFysaB1vaBT1ZTYBPpwRk+3Rw3Icep4/6iM/uOQiAdcC9urYAPtGRv8g8UDIWb76ZUp2Cu+INRjJ+pCOCU78QrqOkJIQJ9KJPbsRiYvB2kW9G2RWRoFM3fSh4lUKh41ESwM6DmnlmYAjMrApCfDO0PSCWFAw02aVT4umOR7e2xG9/kMUprOVQgXLN4arNWEgPfwggxtsKNM7NR61hHdBV6nOuKZnueYT6WtY1oTwvnRhuivImMQQ3jwqsPGT+VqMfESd1Awq6/bXhZKppZxd1UCY/MIuOVHrJ66MV7oOnzQxJkKexe4/wklgShGzbOyWGO7w30dSY4uYJ/mEu+qPlMlO5hpB0EDLlGzKkNmC5Q4QIrgAIevputg7PKGdALIPMNDiFP3/OJ9FmwnYYwUazpn41B15T/bAE2SDOwImws4D647WpIuweFTlbRM2Jl1cPpuWccxY3LHIIKfEjQKiFDyfLJ7OVulMJeUgXGEYyq6OFIF9/aBG53s2h3IqyIlTkwkuzWLvc8PNk46UyfyBj7Mj4d3Wsqudl5HYqhKD6d2WyGmBXKonZlrZhY5Xy+fC5BjQpYhm5qEVYdEJHON2yoXG8rbZCq/wNZKrzfT8cV6QnkTVT3vPKIwh6A==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-login-secret
      namespace: epix-test
    type: kubernetes.io/dockerconfigjson
