apiVersion: batch/v1
kind: Job
metadata:
  name: configure-minio
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: setup
          image: minio/mc
          env:
            - name: MINIO_ALIAS
              value: tenant
            - name: MINIO_ENDPOINT
              value: "http://minio"
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: develop-minio-tenant-configuration
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: develop-minio-tenant-configuration
                  key: secretKey
          command:
            - /bin/sh
            - -c
            - |
              echo "Waiting for MinIO to be ready..."
              until mc alias set "$MINIO_ALIAS" "$MINIO_ENDPOINT" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"; do
                echo "Waiting..."
                sleep 5
              done
              echo "Setting policy..."
              mc mb tenant/develop-ehrshow-images || true
              mc anonymous set download tenant/develop-ehrshow-images
